name: prizorsdk_flutter
description: Prizor SDK Flutter is a powerful Flutter plugin that seamlessly integrates with PrizorSDK, providing advanced features for your mobile applications. This documentation will guide you through the process of integrating and utilizing the PrizorSDK in your Flutter projects.
version: 0.0.2
homepage: https://prizor.com
repository: https://github.com/crmall/prizorsdk_flutter

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.3
  encrypt: ^5.0.1
  permission_handler: ^10.3.0
  collection: ^1.17.1
  flutter_inappwebview: ^6.0.0-beta.24+1
  device_info_plus: ^9.0.2

  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: